### ISSUE TITLE
引入氦气以减轻重力方向的压力

### ISSUE THREAD

**Issue by zenozeng** [QSCTech/drone#1]

**Comment by Hexcles** [comment]
卧槽这到底是啥……

**Comment by Senorsen** [comment]
@hexcles 无人机计划！！
@coxious 窝在有空时将参与！

**Comment by xqyww123** [comment]
那不会很大么…？

**Comment by richard1122** [comment]
是真的无人机还是游戏…

**Comment by Senorsen** [comment]
@richard1122 真的，硬件。

**Comment by Hexcles** [comment]
http://droneproject.org/

2014-10-14 21:31 GMT-07:00 Zeno Zeng notifications@github.com:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/QSCTech/drone/issues/1.

## 

Robert Ma (Hexcles)
Github: https://github.com/Hexcles/
Blog: http://robotshell.org/

**Comment by Senorsen** [comment]
@Hexcles 看起来不错~只是木有英文
不过不知道它可以用什么信号？窝们考虑过各种控制信号、视讯信号的承载方式，还是有一些不确定。。

**Comment by zenozeng** [comment]
似乎不大靠谱
